#!/bin/sh

# CLEAR THE CLI
clear 


# CONTINUE ONLY IF ROOT USER!
sUserName=$(whoami)

if [ "$sUserName" != "root" ] ; then

	echo ""
	echo "PSMPS Start Install Script"
	echo ""		

	echo "You must be a root user to execute this script!"
	echo "Please execute 'su' in terminal, enter the root"
	echo "password, and execute this script again!"
	echo ""

	exit 1

fi



#clear all logs
rm -f /var/log/psmps-*


#STAY IN ROOT FOLDER AND USE ABSOLUTE PATHS
cd /  > /var/log/psmps-install

echo "PSMP MAIN INSTALL STARTED" >> /var/log/psmps-install






until [ "$sContinue" = "yes" ]
do
	
	if [ "$sContinue" = "quit" ] ; then
		
		echo "PSMP INSTALL ABORTED BY USER (startInstall Script)" >> /var/log/psmps-install

		clear

		echo ""
		echo "PSMPS Start Install Script"
		echo ""

		echo "You may install later using /PSMPS/psmps-install"
	
		echo "Sorry you've got to leave :( See you next time!"
		echo ""

		exit 0		
		
	else #### ELSE ######
	
		#CLEAR THE CLI
		
		clear
		
		echo ""
		echo "PSMPS Start Install Script"
		echo ""
		
		if [ "$sContinue" != "" ] ; then
			echo "You must put in exactly 'yes', or 'quit'"
                	echo ""			
		fi
		echo "WARNING: THIS WILL DELETE OLD PSMPS DIR AND RE-GIT A NEW ONE!"
		echo "         Quit now and make backups of your configs!"
		echo ""
		echo "ReGit of the project is mandatory (because of updates)"
		echo ""
		echo "Main Install Log is inside /var/log/psmps-install"
		echo "" 		
		echo "Continue with install? Please type 'yes' or 'quit'."
	        read sContinue
		sContinue=`echo $sContinue | tr [:upper:] [:lower:]`
        	echo ""
		
	
	fi


done

echo "" >> /var/log/psmps-install
echo "FLUSHING PSMPS LOGS" >> /var/log/psmps-install
echo "" >> /var/log/psmps-install

rm -f /var/log/psmps*

echo "" >> /var/log/psmps-install
echo "Starting ReGit!" >> /var/log/psmps-install
echo "ReGit Log is inside /var/log/psmps-regit.log" >> /var/log/psmps-install
echo "" >> /var/log/psmps-install

cp psmps-x-scriptonly-regitproject / >> /var/log/psmps-install




# Add link in init.d to startup script

`ln -s /PSMPS/init.d/psmps /etc/init.d/psmps`

# Add links to the rc3.d rc4.d and rc5.d -- beacause update-rc.d wont work some reason. manual add.

`ln -s /PSMPS/init.d/psmps /etc/rc2.d/S09psmps`
`ln -s /PSMPS/init.d/psmps /etc/rc3.d/S09psmps`
`ln -s /PSMPS/init.d/psmps /etc/rc4.d/S09psmps`
`ln -s /PSMPS/init.d/psmps /etc/rc5.d/S09psmps`



echo ""
echo " Everything Graavvvvyyyy up til here :) "
echo ""
echo ""
echo "END OF THIS SCRIPT! THANK YOU FOR PURCHASING,"
echo "USING, AND SUPPORTING MY SCRIPT!"
echo ""
echo "kthx / kthxbai2u / kthxdie / Shawn Read"
echo "http://www.PoolServ.info/"
echo ""
echo ""
echo "LOGS inside /var/log/ directory"
echo "cat /var/log/psmps-*"
echo ""
echo ""

sleep 4

chmod +x /PSMPS/scripts/psmps-x-scriptonly-regitproject >> /var/log/psmps-install

psmps-x-scriptonly-regitproject

exit 0
