#!/bin/sh

# CLEAR THE CLI
clear 




echo "PSMP INSTALL STARTED (startInstall Script)" > /var/log/psmps-install.log
echo "" >> /var/log/psmps-install.log
echo "Main Install Log is inside /var/log/psmps-install"
echo "" >> /var/log/psmps-install.log

sleep 4


# CONTINUE ONLY IF ROOT USER!
if [[ $EUID -ne 0 ]]; then

	echo "PSMP INSTALL START FAILED - NOT ROOT! (startInstall Script)" >> /var/log/psmps-install.log

	echo ""
	echo "PSMPS Start Install Script"
	echo ""		

	echo "You must be a root user to execute this script!"
	echo "Please execute 'su' in terminal, enter the root"
	echo "password, and execute this script again!"
	echo ""

	exit 1

fi


sContinue=SGISDIFgSDFgikjsdGikdFHfgh

until [ "$sContinue" = "yes" ]
do
	
	if [ "$sContinue" = "quit" ] ; then
		
		echo "PSMP INSTALL ABORTED BY USER (startInstall Script)" >> /var/log/psmps-install.log

		clear

		echo ""
		echo "PSMPS Start Install Script"
		echo ""
	
		echo "Sorry you've got to leave :( See you next time!"
		echo ""

		exit 0		
		
	else #### ELSE ######
	
		#CLEAR THE CLI
		
		clear
		
		echo ""
		echo "PSMPS Start Install Script"
		echo ""
		
		if [ "$sContinue" != "SGISDIFgSDFgikjsdGikdFHfgh" ] ; then
			echo "You must put in exactly 'yes', or 'quit'"
                	echo ""			
		fi

		echo "WARNING: THIS WILL DELETE OLD PSMPS DIR AND RE-GIT A NEW ONE!"
		echo "         Quit now and make backups of your configs!"
		echo ""
		echo "ReGit of the project is mandatory (because of updates)"
		echo ""
		echo "Continue with install? (yes/quit)"
	        read sContinue
        	echo ""
		
	
	fi


done

echo "" >> /var/log/psmps-install.log
echo "Starting ReGit!" >> /var/log/psmps-install.log
echo "ReGit Log is inside /var/log/psmps-regit.log" >> /var/log/psmps-install.log
echo "" >> /var/log/psmps-install.log

sleep 4

cp /PSMPS2/scripts/reGitProject / >> /var/log/psmps-install.log

chmod +x /reGitProject >> /var/log/psmps-install.log

/reGitProject
