#!/bin/sh

# CLEAR THE CLI
clear 




# CONTINUE ONLY IF ROOT USER!
if [[ $EUID -ne 0 ]]; then

	echo ""
	echo "PSMPS PreRequisite Install"
	echo ""		

	echo "You must be a root user to execute this script!"
	echo "Please execute 'su' in terminal, enter the root"
	echo "password, and execute this script again!"
	echo ""

	exit 1

fi




Continue=SGISDIFgSDFgikjsdGikdFHfgh

echo ""
echo "PSMPS Install new coin"
echo ""

until [ "$Continue" = "yes" ]
do
	
	if [ "$Continue" = "no" ] || [ "$Continue" = "quit" ] ; then
	
		echo "Sorry you've got to leave :( See you next time!"
		echo ""

		exit 0
	
	else #### ELSE ######
	
		#CLEAR THE CLI
		
		clear
		
		echo ""
		echo "PSMPS PreRequisite Install"
		echo ""
		
		if [ "$Continue" != "SGISDIFgSDFgikjsdGikdFHfgh" ] ; then
			echo "You must put in exactly 'yes', 'no', or 'quit'"
                	echo ""
			
		fi

		echo "Continue? (yes/no/quit)"
	        read Continue
        	echo ""
		
	
	fi


done

echo "YES WAS SELECTED!"

cd stratum/

git clone https://github.com/Crypto-Expert/stratum-mining.git

cd stratum-mining

git submodule init
git submodule update
git checkout maxcoin # <— very important part to get maxcoin branch

cd externals/maxcoin-hash-python/

git clone https://github.com/Prydie/maxcoin-hash-python.git . ## <-- not the . at the end
python setup.py install

cd ../python-sha3
git clone https://github.com/peconi/python-sha3.git . ## <— note a . at the end
python setup.py install

cd ../stratum
git clone https://github.com/peconi/stratum.git . ## <— note a . at the end
python setup.py install

cd ../../../

mv stratum-mining/* ./
rm -rf stratum-mining

cd ..
