#!/bin/sh

# CLEAR THE CLI
clear

#
#
#
#	Git my project - SKIP ONLY IF YOU GIT'd WITHIN THE PAST FEW HOURS
#
#
#

echo ""
echo "PSMPS ReGit Script"
echo "PSMPS ReGit Script" >> /var/log/psmps-install.log
echo ""

echo "Attempting ReGit"
echo "Attempting ReGit" >> /var/log/psmps-install.log
echo ""


# Change to root dir

cd /  >> /var/log/psmps-install.log

# SUGGEST WIPING OLD INSTALL
# COMMENTED so you don't accidentally paste it in
#

rm -rf /PSMPS2  >> /var/log/psmps-install.log


echo "GITTING PROJECT"
echo "GITTING PROJECT" >> /var/log/psmps-install.log
echo ""

git clone https://github.com/kthxbai2u/PSMPS.git /PSMPS2/ >> /var/log/psmps-install.log

echo "CHMODDING FILES"
echo "CHMODDING FILES" >> /var/log/psmps-install.log
echo ""

# Chmod and Chown folders
chown -R www-data:www-data /PSMPS2 >> /var/log/psmps-install.log
chmod -R 775 /PSMPS2 >> /var/log/psmps-install.log
chmod -R 777 /PSMPS2/mining-servers/ >> /var/log/psmps-install.log
chmod -R 777 /PSMPS2/logs/ >> /var/log/psmps-install.log
chmod -R 777 /PSMPS2/scripts/ >> /var/log/psmps-install.log

# This will allow any user to read all directories, 
# and the user/group read/write. Permissions will
# be further set later on.

echo ""
echo "Completed ReGit"
echo ""
echo "Starting PreRequisite Install"

sleep 10

cd /PSMPS2/scripts/ >> /var/log/psmps-install.log

chmod +x installPreRequisites >> /var/log/psmps-install.log

./installPreRequisites >> /var/log/psmps-install.log

