#!/bin/sh
### BEGIN INIT INFO
# Provides:       psmps daemon
# Required-Start: $network $named $syslog $time
# Should-Start: cyrus ldap ypbind openslp
# Required-Stop:
# Default-Start:  2 3 4 5
# Default-Stop:	  0 1 6
# Description:    start the PSMPS daemon
### END INIT INFO


case $1 in
	start)
		/PSMPS/scripts/psmps-startdaemons
	;;
	stop)
		#not sure yet
		echo "No Brakes!!! Cannot stop!"
	;;
	restart)
		#not sure yet
		echo "No Brakes!!! Cannot stop!"
	;;
	status)
		
		/PSMPS/scripts/psmps-showwalletinfo
		
	;;
	*)
		echo "Usage: /etc/init.d/apache2$DIR_SUFFIX {start|stop|restart|status}"
		exit 1
	;;
esac
